### ISSUE TITLE
How do you Reset it?

### ISSUE THREAD

**Issue by Gfurst** [marisukukise/japReader#4]
Wondering how can you reset what are known/ignored words and whatnot, already tried to delete the local files, unless I got the wrong ones.

Also wondering about the word count feature, would be interesting to elaborate on it, but I don't know if there is any indication.

**Comment by marisukukise** [comment]
The file that stores words `status_data.json` should be in the `data` folder
Deleting it doesn't work from what I see, because the program expects json data to be in there (even if those are empty arrays) and that's actually a bug that I will fix. Instead, change the contents of `status_data.json` to:
```js
{
    "seen": [],
    "known": [],
    "ignored": []
}
```

And I don't understand your question about word count feature.

**Comment by Gfurst** [comment]
Thanks, I'll try that out, as it turns out, I'm on linux and I thought the local user files were stored in ~/.config/japanese-reader

As for the word, as one would expect from a language learning aid, I would think its some sort of daily target to reach? That's also why I think you could elaborate more (in the readme) on what its meant to be.

**Comment by marisukukise** [comment]
If you mean the "goal" and "streak days", then that's a feature that already was in the software when I forked it and as far as I know it didn't work when I forked it. So for now it doesn't work and it hasn't been my priority to fix it. I will either fix it or remove it.

**Comment by marisukukise** [comment]
Fixed in https://github.com/marisukukise/japReader/releases/tag/v1.5.0
Now the config is stored in ~/.config/japreader/config and you can reset the settings by either deleting the file, or through GUI in the options menu
